### ISSUE TITLE
Add support for NDNLP packets

### ISSUE THREAD

**Issue by JonnyKong** [named-data/python-ndn#20]
Currently, python-ndn does not handle [NDN link protocol packets](https://redmine.named-data.net/projects/nfd/wiki/NDNLPv2#NDNLPv2), except NACK. 

For example, when the network gets congested, NFD will wrap Interest/Data packets in NDNLP packet with congestion markings. The python-ndn library currently discards the packet, and shows a warning message as follows:

```
WARNING:Unable to decode received packet
```

I have attached an example NDNLP packet here: [packet.zip](https://github.com/named-data/python-ndn/files/5498113/packet.zip)

**Comment by zjkmxy** [comment]
Will fix this ASAP.

**Comment by yoursunny** [comment]
NDNLP has a "critical vs non-critical TLV-TYPE" distinction. If you don't want to handle congestion mark, you can ignore it since it has a non-critical TLV-TYPE number. On the other hand, if you are unable to handle PIT token or fragmentation, you have to drop the packet as those have critical TLV-TYPE numbers.

**Comment by susmit85** [comment]
Hi, can we please fix this? We don't want to rely on application retransmission since that adds to congestion.

**Comment by zjkmxy** [comment]
> Hi, can we please fix this? We don't want to rely on application retransmission since that adds to congestion.

I'm currently working on this. I'm sorry that this may take some time, but you will see it in several weeks.

**Comment by zjkmxy** [comment]
Hello. I just pushed a patch.
Sorry for being late. After I upgraded my Mac, everything was broken ...
I have only tested it in the integration test, but not with NFD yet. (I need to reinstall NFD and fix possible problems which may take more time.)
Please check if it solves the problem or brings more bugs. Thanks

**Comment by yoursunny** [comment]
As of b5e60a67ee8b72582b25bb1262e913c09f0cfbe5, the implementation is incorrect.
For example, if a fragmented packet arrives, this implementation would incorrectly accept this packet, despite that it lacks a reassembler.

Please see NDNLPv2 protocol for requirements on processing critical vs non-critical TLV-TYPE numbers. It differs from evolvability rules of NDN network layer packets.

**Comment by zjkmxy** [comment]
This implementation does not handle fragmentation yet. Will be added later.

**Comment by yoursunny** [comment]
> This implementation does not handle fragmentation yet. Will be added later.

You missed the point. It's OK to not handle a certain NDNLPv2 field that has a critical TLV-TYPE number, but then the decoder MUST drop any NDNLPv2 frame that uses such field.
